apiVersion: v1
data:
  POSTGRES_DB: "{{ .Values.application.db }}"
kind: ConfigMap
metadata:
  name: "{{ include "product-db.name" . }}-configmap"
  namespace: {{ .Values.environment }}
  labels:
    {{- include "product-db.labels" . | nindent 4 }}
