apiVersion: v1
data:
  POSTGRES_USER: "{{- .Values.application.dbUsername | b64enc }}"
  POSTGRES_PASSWORD: "{{- .Values.application.dbPassword | b64enc }}"
kind: Secret
metadata:
  name: "{{ include "product-db.name" . }}-secrets"
  namespace: {{ .Values.environment }}
  labels:
    {{- include "product-db.labels" . | nindent 4 }}
type: Opaque
