apiVersion: v1
kind: Service
metadata:
  # name: {{ include "product-db.fullname" . }}
  name: {{ include "product-db.name" . }}
  labels:
    {{- include "product-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "product-db.selectorLabels" . | nindent 4 }}
