apiVersion: v1
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.application.database.host }}:{{ .Values.application.database.port }}/{{ .Values.application.database.name }}"
kind: ConfigMap
metadata:
  name: "{{ include "product-api.name" . }}-configmap"
  namespace: {{ .Values.environment }}
  labels:
    {{- include "product-api.labels" . | nindent 4 }}
