apiVersion: v1
data:
  SPRING_DATASOURCE_USERNAME: "{{- .Values.application.database.username | b64enc }}"
  SPRING_DATASOURCE_PASSWORD: "{{- .Values.application.database.password | b64enc }}"
kind: Secret
metadata:
  name: "{{ include "product-api.name" . }}-secrets"
  namespace: {{ .Values.environment }}
  labels:
    {{- include "product-api.labels" . | nindent 4 }}
type: Opaque
