version: '3.8'
name: product
services:
  product-api:
    image: 'product-api:latest'
    container_name: product-api
    # restart: unless-stopped
    ports:
      - '8000:8080'
    depends_on:
      - product-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=motdepasse
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  product-db:
    image: 'postgres:15-alpine'
    # restart: unless-stopped
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_DB=productdb
    ports:
      - '5432:5432'
    volumes:
      - 'product-db:/var/lib/postgresql/data'
volumes:
  product-db: null